"""
PDF Audit Report Generator
Uses ReportLab to generate publication-grade, structured PDF compliance audit reports.
"""

from typing import List
import os
import html
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from ..core.models import AuditReport, CheckStatus


class PDFReportGenerator:
    """Builds a formal PDF accessibility audit report."""

    @staticmethod
    def generate(report: AuditReport, output_filepath: str):
        doc = SimpleDocTemplate(
            output_filepath,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()

        # Custom paragraph styles
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=20,
            leading=24,
            textColor=colors.HexColor('#0f172a'),
            spaceAfter=4
        )

        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            textColor=colors.HexColor('#64748b'),
            spaceAfter=15
        )

        h2_style = ParagraphStyle(
            'SectionH2',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=16,
            textColor=colors.HexColor('#1e293b'),
            spaceBefore=12,
            spaceAfter=6
        )

        cell_style = ParagraphStyle(
            'CellText',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#1e293b')
        )

        cell_bold = ParagraphStyle(
            'CellBold',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=10,
            textColor=colors.HexColor('#0f172a')
        )

        story = []

        # 1. Header
        story.append(Paragraph("PDF Accessibility Compliance Audit Report", title_style))
        story.append(Paragraph(f"Generated by PDF Accessibility Inspector | Date: {html.escape(str(report.timestamp))}", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563eb'), spaceAfter=12))

        # 2. Executive Summary & Document Metadata Box
        d_info = report.document_info
        score = report.compliance_score
        score_hex = '#10b981' if score >= 90 else ('#f59e0b' if score >= 70 else '#ef4444')

        meta_data = [
            [
                Paragraph("<b>File Name:</b>", cell_style),
                Paragraph(html.escape(str(d_info.get("filename", ""))), cell_style),
                Paragraph("<b>Compliance Score:</b>", cell_style),
                Paragraph(f"<font color='{score_hex}'><b>{score}%</b></font>", cell_bold)
            ],
            [
                Paragraph("<b>Document Title:</b>", cell_style),
                Paragraph(html.escape(str(d_info.get("title", "Untitled"))), cell_style),
                Paragraph("<b>PDF Version:</b>", cell_style),
                Paragraph(html.escape(str(d_info.get("pdf_version", "1.7"))), cell_style)
            ],
            [
                Paragraph("<b>Pages / Size:</b>", cell_style),
                Paragraph(f"{d_info.get('page_count', 0)} pages ({round(d_info.get('filesize', 0)/1024, 1)} KB)", cell_style),
                Paragraph("<b>Language:</b>", cell_style),
                Paragraph(html.escape(str(d_info.get("language", "Not specified"))), cell_style)
            ],
            [
                Paragraph("<b>Tagged PDF:</b>", cell_style),
                Paragraph("Yes" if d_info.get("is_tagged") else "<font color='#ef4444'><b>No</b></font>", cell_style),
                Paragraph("<b>PDF/UA Declared:</b>", cell_style),
                Paragraph("Yes" if d_info.get("pdfua_declared") else "No", cell_style)
            ],
        ]

        meta_table = Table(meta_data, colWidths=[100, 180, 110, 150])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#f1f5f9')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 14))

        # 3. Overall Statistics Counters Table
        stat_data = [
            [
                Paragraph("<b>TOTAL CHECKS</b>", cell_bold),
                Paragraph("<b>PASSED</b>", cell_bold),
                Paragraph("<b>WARNINGS</b>", cell_bold),
                Paragraph("<b>FAILED ISSUES</b>", cell_bold),
                Paragraph("<b>MANUAL REVIEW</b>", cell_bold),
            ],
            [
                Paragraph(f"<b>{len(report.results)}</b>", cell_bold),
                Paragraph(f"<font color='#166534'><b>{report.total_passed}</b></font>", cell_bold),
                Paragraph(f"<font color='#92400e'><b>{report.total_warned}</b></font>", cell_bold),
                Paragraph(f"<font color='#991b1b'><b>{report.total_failed}</b></font>", cell_bold),
                Paragraph(f"<font color='#075985'><b>{report.total_manual}</b></font>", cell_bold),
            ]
        ]
        stat_table = Table(stat_data, colWidths=[108, 108, 108, 108, 108])
        stat_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
            ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#ffffff')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#cbd5e1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(stat_table)
        story.append(Spacer(1, 14))

        # 4. Standards Summary Table
        story.append(Paragraph("Standards Evaluation Summary", h2_style))
        summary_rows = [
            [
                Paragraph("<b>Standard</b>", cell_bold),
                Paragraph("<b>Checkpoint Category</b>", cell_bold),
                Paragraph("<b>Passed</b>", cell_bold),
                Paragraph("<b>Warned</b>", cell_bold),
                Paragraph("<b>Failed</b>", cell_bold),
                Paragraph("<b>Manual</b>", cell_bold),
            ]
        ]

        for std in ["PDF/UA", "WCAG", "Quality", "AI"]:
            cat_counts = report.get_category_counts(std)
            for cat, counts in cat_counts.items():
                p_c = counts['passed']
                w_c = counts['warned']
                f_c = counts['failed']
                m_c = counts['manual']
                summary_rows.append([
                    Paragraph(html.escape(std), cell_style),
                    Paragraph(html.escape(cat), cell_style),
                    Paragraph(f"<font color='#166534'>{p_c}</font>", cell_style),
                    Paragraph(f"<font color='#92400e'>{w_c}</font>" if w_c else "0", cell_style),
                    Paragraph(f"<font color='#991b1b'><b>{f_c}</b></font>" if f_c else "0", cell_style),
                    Paragraph(f"<font color='#075985'>{m_c}</font>" if m_c else "0", cell_style),
                ])

        sum_table = Table(summary_rows, colWidths=[70, 230, 60, 60, 60, 60])
        sum_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f8fafc')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#f1f5f9')),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(sum_table)
        story.append(Spacer(1, 14))

        # 5. Detailed Problem Findings (Failures and Warnings)
        problems = [r for r in report.results if r.status in (CheckStatus.FAIL, CheckStatus.WARNING, CheckStatus.ERROR)]
        story.append(Paragraph(f"Detailed Issues & Remediation Action Items ({len(problems)})", h2_style))

        if not problems:
            story.append(Paragraph("<font color='#166534'><b>Congratulations! No accessibility failures or warnings were detected.</b></font>", cell_style))
        else:
            prob_rows = [
                [
                    Paragraph("<b>Status</b>", cell_bold),
                    Paragraph("<b>Rule ID</b>", cell_bold),
                    Paragraph("<b>Standard</b>", cell_bold),
                    Paragraph("<b>Pg</b>", cell_bold),
                    Paragraph("<b>Issue & Remediation</b>", cell_bold),
                ]
            ]
            for p in problems:
                color_str = '#991b1b' if p.status == CheckStatus.FAIL else '#92400e'
                name_esc = html.escape(str(p.name or ""))
                msg_esc = html.escape(str(p.message or ""))
                desc_text = f"<b>{name_esc}</b>: {msg_esc}"
                if p.evidence:
                    ev_esc = html.escape(str(p.evidence or ""))
                    desc_text += f"<br/><font color='#64748b'><b>Evidence:</b> {ev_esc}</font>"
                if p.remediation:
                    rem_esc = html.escape(str(p.remediation or ""))
                    desc_text += f"<br/><font color='#166534'><b>Remediation:</b> {rem_esc}</font>"

                prob_rows.append([
                    Paragraph(f"<font color='{color_str}'><b>{p.status.value}</b></font>", cell_style),
                    Paragraph(f"<code>{html.escape(str(p.check_id))}</code>", cell_style),
                    Paragraph(html.escape(str(p.standard)), cell_style),
                    Paragraph(str(p.page or "-"), cell_style),
                    Paragraph(desc_text, cell_style),
                ])

            prob_table = Table(prob_rows, colWidths=[65, 95, 65, 30, 285])
            prob_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f8fafc')),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
                ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ]))
            story.append(prob_table)

        doc.build(story)
